export interface CandidatData {
    id: number;
    name: string;
    image: string;
    experience: string;
    location: string;
    competences: string;
    sector: string;
    disponibilite: boolean;
    email : string;
    
}


const fakeCandidatData : CandidatData[] = [
    {
    id: 1,
    name: "Mickeal",
    image: "Images/avatars/avatar-1.svg",
    experience: "Sénior",
    location: "01 Ain",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "sirinemahjoub80@gmail.com",
    },
    {
    id: 2,
    name: "Mickeal",
    image: "Images/avatars/avatar-5.svg",
    experience: "Sénior",
    location: "05 Hautes-Alpes",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },
    {
    id: 3,
    name: "Mickeal",
    image: "Images/avatars/avatar-20.svg",
    experience: "Junior",
    location: "02 Aisne",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: false,
    email : "mickeal@GiMailShirt.com",
    },
    {
    id: 4,
    name: "Mickeal",
    image: "Images/avatars/avatar-47.svg",
    experience: "Sénior",
    location: "05 Hautes-Alpes",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },
    {
    id: 5,
    name: "Mickeal",
    image: "Images/avatars/avatar-6.svg",
    experience: "Confirmé",
    location: "04 Alpes-de-Haute-Provence",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },
    {
    id: 6,
    name: "Mickeal",
    image: "Images/avatars/avatar-12.svg",
    experience: "Sénior",
    location: "01 Ain",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },
    {
    id: 7,
    name: "Mickeal",
    image: "Images/avatars/avatar-22.svg",
    experience: "Junior",
    location: "01 Ain",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: false,
    email : "mickeal@GiMailShirt.com",
    },
    {
    id: 8,
    name: "Mickeal",
    image: "Images/avatars/avatar-30.svg",
    experience: "guru",
    location: "08 Ardennes",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },
    {
        id: 9,
    name: "Mickeal",
    image: "Images/avatars/avatar-1.svg",
    experience: "Sénior",
    location: "05 Hautes-Alpes",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },

    {
        id: 10,
    name: "Mickeal",
    image: "Images/avatars/avatar-1.svg",
    experience: "Débutant",
    location: "06 Alpes-Maritimes",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },
    {
        id: 11,
    name: "Mickeal",
    image: "Images/avatars/avatar-17.svg",
    experience: "Sénior",
    location: "04 Alpes-de-Haute-Provence",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@GiMailShirt.com",
    },
    {
        id: 12,
    name: "Mickeal",
    image: "Images/avatars/avatar-45.svg",
    experience: "Confirmé",
    location: "01 Ain",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: true,
    email : "mickeal@gmail.com",
    },
    {
        id: 13,
    name: "Mickeal",
    image: "Images/avatars/avatar-39.svg",
    experience: "Débutant",
    location: "08 Ardennes",
    competences: "C Embedded",
    sector: "Aéronautique",
    disponibilite: false,
    email : "mickeal@GiMailShirt.com",
    },
];
export default fakeCandidatData;